### ISSUE TITLE
  headers.Authorization = `Bearer ${this.token}` is giving problem sending http requests

### ISSUE THREAD

**Issue by fabriziogianni7** [filecoin-shipyard/js-lotus-client-provider-browser#28]
Hey guys,
we use this library in https://plus.fil.org/ and this [line](https://github.com/filecoin-shipyard/js-lotus-client-provider-browser/blob/48e20db663bb47f9f9944fad0c90e508215324e5/index.js#L82) is giving problem when sending http requests towards the node.
can we find a solution on that?

**Comment by jimpick** [comment]
I’m not really the maintainer on this package anymore.

I’m not sure I understand though … if you don't define the token option, then that header won't be included. There’s an if statement around that code. There's also an `authorizationHeader` that can be set instead.

**Comment by fabriziogianni7** [comment]
you're right. I removed the token and it's working. I'll close this, thanks a lot 👍
